### ISSUE TITLE
Empty result from "Jd all <empty series>"; P deletes cached images for empty series

### ISSUE THREAD

**Issue by anaconda** [MilhouseVH/texturecache.py#25]
Hey - it seems the script doesn't handle empty series (i.e. existing shows with no episode) correctly.

I have this "Arrow" without episodes. I would expect "Jd" to return arts, label, tvshowid (generic infos for the TV show) if it doesn't have episodes, but is found in the database. I don't get anything currently (as if it doesn't exist at all):
```
anepu:fake-source anaconda$ ~/texturecache.py Jd all Arrow
anepu:fake-source anaconda$
```

Also, "P" removes cached images (banner, fanart, ...) for empty shows. I would expect it to delete textures only if the show doesn't exist.

Edit: hmm well, for Jd it doesn't show anything because VideoLibrary.GetTVShows doesn't return anything:
```json
{"jsonrpc": "2.0", "params": {"sort": {"order": "ascending", "method": "title"}, "filter": {"operator": "contains", "field": "title", "value": "Arrow"}, "properties": ["title", "art", "file"], "limits": {"start": 0, "end": 400}}, "method": "VideoLibrary.GetTVShows", "id": "libTvshows"}
{"id":"libTvshows","jsonrpc":"2.0","result":{"limits":{"end":1,"start":0,"total":1}}}
```
Interesting...

**Comment by anaconda** [comment]
Ah, didn't think having "Fixes otherrepo/#" would actually close the issue there automatically.
Btw no change is needed. Honoring `videolibrary.showemptytvshows` (via `Settings.GetSettingValue`) would be a nice-to-have, or not.

**Comment by MilhouseVH** [comment]
For now I'm not going to make any changes - if anyone wants to exclude tvshows that have no episodes then I can consider adding a property and/or supporting the GUI setting but I suspect it's not likely to be needed. Returning shows without episodes even when they're hidden fixes this issue and is likely to be what most users will want from this script.
