### ISSUE TITLE
Turning off HDMI in different ways when started via command line or systemd. 

### ISSUE THREAD

**Issue by leetwanker** [MilhouseVH/texturecache.py#26]
Most likely it's due to an error I've made in how I'm starting it with systemd but I wanted to get your opinion on it. 

When started from command line it's using /opt/vc/bin/vcgencmd display_power 0 / 1 (As it should)
[texturecache.commandline.log](http://pastebin.com/raw.php?i=s2CBmNLq)

When started with systemd on OSMC it's using /opt/vc/bin/tvservice --off / --preferred 
[texturecache.systemd.log](http://pastebin.com/raw.php?i=3J4jZdhf)

Here's my systemd config:
[texturecache.timer & texurecache.service](http://pastebin.com/raw.php?i=ufgFwH55)

Let me know if you need any further info or if you'd like me to test anything. Glad to help out!

**Comment by MilhouseVH** [comment]
> When started with systemd on OSMC it's using /opt/vc/bin/tvservice --off / --preferred
> texturecache.systemd.log

Your path when using systemd doesn't include /opt/vc/bin so the script can't find vcgencmd - in your log, see:
```
  "BIN_CECCONTROL": "", 
  "BIN_TVSERVICE": "/opt/vc/bin/tvservice", 
  "BIN_VCGENCMD": null, 
```
and `BIN_VCGENCMD` is `null`, ie. it can't be found so won't be called.

Either add `@bin.vcgencmd=/opt/vc/bin/vcgencmd` when calling the script, or fix your PATH environment variable by adding `/opt/vc/bin`.

**Comment by leetwanker** [comment]
Thanks very much Milhouse! Great script you've made. Working perfectly on OSMC now and I've posted how I did it on OSMC.tv and Kodi.tv.
