### ISSUE TITLE
Add feature to list unindexed files

### ISSUE THREAD

**Issue by Phlogi** [MilhouseVH/texturecache.py#28]
An option, maybe for vscan, to show all media files that are not indexed by kodi would be a good enhancement. 

This can be implemented according to the script here:

http://kodi.wiki/view/Linux-Script_To_Find_Not_Scraped_Movies

Thanks for considering this :)

**Comment by MilhouseVH** [comment]
Already there.

`texturecache.py missing movies|tvshows|songs <sources>`

eg.
`texturecache.py missing movies "my movies"`
`texturecache.py missing tvshows "my tvshows"`
`texturecache.py missing songs "my music"`

**Comment by Phlogi** [comment]
Awesome, thanks - I did overlook that.
