### ISSUE TITLE
json profiles

### ISSUE THREAD

**Issue by un1versal** [MilhouseVH/texturecache.py#30]
Isnt https://github.com/MilhouseVH/texturecache.py/blob/master/texturecache.py#L517-L518
this https://github.com/xbmc/xbmc/pull/2049

**Comment by MilhouseVH** [comment]
No. If `directory` were supported it would be used [here](https://github.com/MilhouseVH/texturecache.py/blob/master/texturecache.py#L7681-L7682). Which is to say, if supported then Kodi would return the working directory path for the specified profile.

I don't remember where the discussion about this field took place (if it ever took place - perhaps I just assumed it would be a good idea and added support, albeit disabled), but it appears to have gone nowhere as the only supported fields when querying profiles remain "thumbnail" and "lockmode" (see [here](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L962-L964)).

As far as this script is concerned, the path for a profile is based on the `@profile.name` relative to `userdata/profiles`, but if `@profile name` doesn't match the folder name (it sometimes doesn't) then the folder name can be specified using `@profile.directory`. Obviously none of this would be necessary if `directory` were a supported field when querying the profile.

**Comment by un1versal** [comment]
Im asking about the PR that introduced that...

**Comment by MilhouseVH** [comment]
In that case I'm not sure what the question is - the PR you linked (which introduces basic profile support and pre-dates the support I added to the script on 29 Oct 2014) doesn't include support for the `directory` field, and as far as I know no such PR exists that adds the required support.

Querying JSON for the profile directory is a feature I thought might be added at some point (possibly based on #irc, forum or trakt discussion hence why I added it but left it disabled) but it remains unsupported to this day.

**Comment by un1versal** [comment]
aahhh. nm then that clears that up.

**Comment by MilhouseVH** [comment]
https://github.com/xbmc/xbmc/pull/8196 just added.

Will push updated texturecache.py support once 8196 merges as this will make the `profile.directory` setting redundant (the setting will be ignored once the directory value is available from JSON).
