### ISSUE TITLE
Errors for every file it attempts to download

### ISSUE THREAD

**Issue by atwright147** [MilhouseVH/texturecache.py#36]
Hey,

When I run `./texturecache.py C movies` it accurately figures out what needs caching but the realtime status message gradually builds a large number of errors (807) and the caching does not take place.

The status message suggests that it is downloading:

```
... 2 threads active (01.28 downloads per second, ETA: 00:12:55)
```

I am running the latest OSMC on a RPi 3

Any help would be much appreciated :)

**Comment by MilhouseVH** [comment]
The script is simply downloading the artwork from Kodi. If Kodi returns an error or is unable to satisfy the request, then it's Kodi that can't access/download the artwork so look in your Kodi log for details and resolve the issue that is preventing Kodi from accessing the artwork (it might be the artwork no longer exists at the specific URL, or it's a file permission error etc.)

In future please post help requests in the Kodi Forum thread.
