### ISSUE TITLE
Request: Exclude list for missing feature

### ISSUE THREAD

**Issue by inspector71** [MilhouseVH/texturecache.py#38]
Would it be possible to include a config variable of strings to exclude from the missing feature? This would help remove bloat such as the inclusion of files with the following common, but probably irrelevant, patterns:

```
^uTorrent*.dat$
^*sample*.*$
```
_Please excuse the rushed hybrid of CLI and Regex syntax_

**Comment by MilhouseVH** [comment]
I've added `missing.ignore.patterns` in v2.3.2.

Using your example you would need to set the following in `texturecache.cfg`:
```
missing.ignore.patterns = ^uTorrent.*\.dat$,^.*sample.*\..*$
```
Each regex in the list will be applied (searched) against only the filename of each candidate file, and not the path - if there is a match the file will be ignored.

**Comment by inspector71** [comment]
Looks like it works very well. Thanks!
