### ISSUE TITLE
Clear cruft from path and files tables as part of vclean

### ISSUE THREAD

**Issue by lozbrown** [MilhouseVH/texturecache.py#40]
Despite using vclean regularly there are a huge number of records in both the path and files tables in the database that no longer exist. I can see these when I view my database with mysql. 

This is particularly prevalent in my "Unsorted" folder where I keep freshly downloaded stuff before sorting it into my preferred file structure where it will be scanned to the library. these folders have often long since disapeered and are not exspected to re-emerge

So for example
in paths i have things like

```
mysql> select idPath,strPath from path where strPath like "%Unsorted%" limit 600;
                                                                                         |
|   3265 | /media/media3/Unsorted-Downloads/Movie.2015.HC.HDRip.XViD.AC3-juggs[ETRG]/
|   3282 | /media/media3/Unsorted-Downloads/Other_Movie.2015.1080p.BluRay.x264-SPARKS[rarbg]/
```

Technically these are not in the library as there is no record in movies or tvshows.

Could we clear this cruft...

**Comment by lozbrown** [comment]
reading the code perhaps this is an issue of incompatibility with the mysql database?

**Comment by MilhouseVH** [comment]
There is no Kodi API to remove rows from `path` and `files` tables, so there's nothing texturecache.py can do here. If these tables are to be cleaned they should be cleaned during the normal Kodi library clean process, which makes it a Kodi core issue.

I would suggest creating a Kodi [feature request](http://forum.kodi.tv/forumdisplay.php?fid=9) or (if this were to be viewed as a bug) a [trac ticket](http://trac.kodi.tv/).

**Comment by MilhouseVH** [comment]
Closing as invalid.
