### ISSUE TITLE
Doesn't seem to work with 17beta5

### ISSUE THREAD

**Issue by graysky2** [MilhouseVH/texturecache.py#41]
The command seems to hang indefinetly when running against 17beta5:
```
% texturecache vclean
```

Can you reproduce or is this unique to my system?

**Comment by MilhouseVH** [comment]
No problems here.

Enable kodi debug logging, then run `texturecache.py vclean @logfile=tc.log`, then paste links to kodi.log and tc.log.

By default the GUI progress dialogs will be hidden when running `texturecache.py vclean`. However to enable the progress dialogs use `texturecache.py vclean @clean.showdialogs=yes`, as this may then show more information or suggest a reason for the hang. One possibility that comes to mind is that Kodi could be prompting for user input during the clean - user input that is hidden - so the clean process stalls waiting for user input that is never going to be entered. If this is the case, it would be a Kodi "core" bug.

**Comment by graysky2** [comment]
Not sure what happened... with debugging enabled per your suggestion, everything worked as expected.  Sorry for the false alarm.  Closing.
