### ISSUE TITLE
Removed episodes from Kodi

### ISSUE THREAD

**Issue by morriscode** [MilhouseVH/texturecache.py#43]
I ran the following command to update missing artwork and it subsequently removed several episodes from Kodi all together.

/texturecache.py @qaperiod=9999 @qa.fail.missinglocalart=yes qax tvshows "nameofshow"

Any idea how to get them back without rebuilding the entire database?

**Comment by MilhouseVH** [comment]
`texturecache.py vscan` will re-scan your library.

`qax` should have automatically re-scanned the episodes after removing them. Without a log file (`@logfile=tc.log`) or even console output, I don't know what happened in your case (why did the episodes fail QA?) or why the episodes were not automatically re-scanned.

If it happens again please post on the Kodi forum thread, with logfiles and console output.
