### ISSUE TITLE
Error when using 'p'

### ISSUE THREAD

**Issue by AnthonyAMC** [MilhouseVH/texturecache.py#44]
I haven't tried any other options, but since all i wanted to do was prune unused cache items, i figured i'd start with the dryrun prune option. This is the output:
```
anthony@build:~/Downloads$ ./texturecache.py p
Loading Albums: George Thorogood And The Delaware Destroyers (Bonus Track VersioLoading Albums: Maverick...                                                     Parsing Songs: Your Love [Originally from the movie 'Once Upon A Time In The WesLoading Genres...                                                               Traceback (most recent call last):eason 1...                            
  File "./texturecache.py", line 8585, in <module>
    main(sys.argv[1:])
  File "./texturecache.py", line 8412, in main
    pruneCache(remove_nonlibrary_artwork=False)
  File "./texturecache.py", line 6515, in pruneCache
    (libraryFiles, mediaFiles) = getAllFiles(keyFunction=getKeyFromFilename)
  File "./texturecache.py", line 6826, in getAllFiles
    for episode in episodedata["result"]["episodes"]:
KeyError: 'episodes'
```
I think the second line in the paste there is an artifact left on screen from processing. If i maximize the terminal window it's overwritten for some strange reason o.0

**Comment by MilhouseVH** [comment]
I need a logfile to investigate further. Re-run the command with `@logfile=/tmp/tc.log` appended on the command line then zip up /tmp/tc.log and upload it somewhere (dropbox, googledrive etc.), then provide a link. Thanks.

**Comment by AnthonyAMC** [comment]
Ok [here's the zipped log](https://expirebox.com/download/639625b7fd68391777e3a41efe219749.html)

**Comment by MilhouseVH** [comment]
Have you deleted/removed all episodes from Season 1 of the show Adventure Time?

**Comment by MilhouseVH** [comment]
Fix pushed. Thanks for the report/log.

**Comment by AnthonyAMC** [comment]
`p` seems to run as expected now. Thank you for a quick fix :D
