### ISSUE TITLE
.nomedia is not honored

### ISSUE THREAD

**Issue by nrosier** [MilhouseVH/texturecache.py#45]
When checking for missing episodes, texturecache does not honor the .nomedia file and reports files in that directory as missing.

**Comment by MilhouseVH** [comment]
Try the latest version 2.3.7.

In order for `.nomedia` to affect the results of `missing` you will need to enable "Show hidden files and directories" in Kodi settings (Settings > Media > General) otherwise hidden files such as `.nomedia` will not be returned by JSON methods.

**Comment by MilhouseVH** [comment]
If you prefer to have `Show hidden files and directories` disabled in the Kodi GUI, then as a workaround you could use:
```
texturecache.py setsetting filelists.showhidden True
texturecache.py missing tvshows My\ TV\ Shows
texturecache.py setsetting filelists.showhidden False
```

**Comment by nrosier** [comment]
Thanks, I've changed the setting in Kodi and it seems to work.
I will check the 2nd solution tonight. I was thinking along the same lines but hadn't had time to look how to change that settting with your script.
