### ISSUE TITLE
[Ideas] Some suggestions for added functionality

### ISSUE THREAD

**Issue by pitsi** [MilhouseVH/texturecache.py#47]
Dear Maintainer.

Please consider adding the following as functions in texturecache.py

1) One that removes all orpahned dependencies at once. A package is orhaned when no other package has it as a dependency, e.g. the streamlink library in my screenshot which was left behind when I uninstalled the only addon that was using it

![orphan](https://user-images.githubusercontent.com/5880037/34219137-e9f99ec8-e5b8-11e7-9422-2a635064b09e.png)

2) One that deletes all the downloaded packages from the cache (.kodi/addons/packages) and everything in kodi's temp folder (.kodi/temp). 

3) One that deletes user settings for addons that were already removed. E.g. If I remove plugin.video.youtube, kodi will delete .kodi/addons/plugin.video.youtube but it's settings in .kodi/userdata/addon_data/plugin.video.youtube will be left behind.

That's all I can think of now.
Thank you in advance.

**Comment by MilhouseVH** [comment]
@pitsi thanks for the suggestions, but unfortunately none of them will be implemented as Kodi lacks the JSON-RPC methods to remove/uninstall addons (1), delete downloaded packages or temporary files (2), or delete settings (3).

Obviously some of the above requests (2 + 3) could be implemented simply by deleting files at the OS level but this limits the script to running on the same machine as Kodi, and would also be deleting files "behind kodi's back" so I'm not particularly interested in implementing that - I'd rather Kodi offered a method to securely/safely delete files, packages etc. (as it does already when removing textures).

By all means submit a feature request to Kodi to enhance the JSON-RPC API to include file delete and add-on uninstall methods, then maybe this can be revisited. However the better solution would be for the Kodi add-on system to clean up after itself.

**Comment by pitsi** [comment]
All the stuff texturecache can do are json-rpc calls? WOW! Good job putting them in one place and letting me know the limitations

There are 2 more things I would like to suggest, if they are possible
1) Installation of addons. I know I can use something like

kodi-send --action=InstallAddon(plugin.video.youtube) 

but it needs a pair of " " somewhere and I never get it right. How about making it to a simple

texturecache.py install plugin.video.youtube

2) Please make a simple command for issuing a forced update to kodi's addons. Using kodi-send, it is supposed to be

kodi-send --action=UpdateAddonRepos

but it never seems to work. Even the notification, the one that usually pops up when manually checking for updates, does not appear.

**Comment by MilhouseVH** [comment]
Would you plan on coding all the GUI interactions needed to complete the install of an addon?

For instance, if you try to install a language addon, Kodi will prompt you for yes/no confirmation, which you could complete using kodi-send:
```
kodi-send --action=InstallAddon\(plugin.video.youtube\)
sleep 2
kodi-send --action=left
sleep 2
kodi-send --action=select
```
but the delay required may depend on how fast your client is.

By the way to install the add-on using `kodi-send` you need to escape the parenthesis, ie.:
```
kodi-send --action=InstallAddon\(plugin.video.youtube\)
```
and then it should work.

Also, `kodi-send --action=UpdateAddonRepos` is working for me (latest Kodi 18 master). If it's not working for you then maybe start a thread on the forum.

**Comment by pitsi** [comment]
Well, It would be enough for me if the installation command could reach up to the confirmation point. I do not want it to be completely silent and I have no problem pressing what is needed.
Thanks for the tip with the slashes :)

As for the forced update, I will look it up in the logs first to see why I get no notification.
