### ISSUE TITLE
DeprecationWarning in Python 3.7.1

### ISSUE THREAD

**Issue by akyag** [MilhouseVH/texturecache.py#53]
Hi, I am on Python 3.7.1 and getting this warning - 
```
/home/akya/xbmc-Texturecache/texturecache.py:241: DeprecationWarning: encodestring() is a deprecated alias since 3.1, use encodebytes()
  self.WEB_AUTH_TOKEN = base64.encodestring(bytes(token, "utf-8")).decode()
```
If you change the lines 
**241** self.WEB_AUTH_TOKEN = base64.encodestring(bytes(token, "utf-8")).decode()
**243** self.WEB_AUTH_TOKEN = base64.encodestring(token)

to
**241** self.WEB_AUTH_TOKEN = base64.encodebytes(bytes(token, "utf-8")).decode()
**243** self.WEB_AUTH_TOKEN = base64.encodebytes(token)

It works! Sorry I don't know how to make a PR! Thanks :)

**Comment by MilhouseVH** [comment]
Thanks, fixed in 42c95e594b30def8f85d9f18b38906ccb211957d

I haven't changed line 243 as `encodebytes()` is not supported by Python2.
