### ISSUE TITLE
remove musicvideo id not working

### ISSUE THREAD

**Issue by bassdart** [MilhouseVH/texturecache.py#54]
Removing a musicvideo isn't working:
```
$ texturecache jd musicvideos "montage of bugs"
[                              
  {
    "art": {
      "poster": "image://https://i.ytimg.com/vi/qMIIwBqn2fE/maxresdefault.jpg/"
    },
    "file": "nfs://192.168.0.77/data/musik/00-video/downtempo/Orson Hentschel - Montage of Bugs.mp4",
    "label": "Montage of Bugs",
    "musicvideoid": 9213,
    "tag": [],
    "title": "Montage of Bugs"
  }
]

$ texturecache remove musicvideo 9213
ERROR: does not exist - media type [musicvideo] libraryid [9213].
```
After changing the param for getMusicVideoName in line [2854](https://github.com/MilhouseVH/texturecache.py/blob/master/texturecache.py#L2854) from movieid to musicvideoid removing works.
The help text btw does not mention that musicvideos is a valid media class when using j, only found it by trial and error ;-)
Thanks for the nice script, using it since a few years on a daily basis to play videos from the web on kodi (together with youtube-dl).

**Comment by MilhouseVH** [comment]
Thanks, fixed in 2.4.9.

Also be aware of https://github.com/xbmc/xbmc/issues/15613 which I found while testing this change - it's a missing null-check that should be fixed soon (most likely in Kodi 18.2).
