### ISSUE TITLE
Feature Request: add "resume" argument to "play"

### ISSUE THREAD

**Issue by desepticon** [MilhouseVH/texturecache.py#57]
Would it be possible to add a "resume" argument to the "play" function? I've been trying to make some voice activated commands leveraging texturecache.py, but my favorite one - where you can tell Kodi to play a specific movie through a voice command, will only start a movie at the beginning. Thanks!

Here's what I have so far:
https://www.reddit.com/r/shortcuts/comments/axkfog/kodi_control/

**Comment by MilhouseVH** [comment]
Resuming playback (presumably from the saved position) isn't currently supported by the Kodi JSON-RPC API, you'd need to request that resume support is added by Team Kodi for Kodi 19 (this would be a feature request, so best handled on the Kodi Forum).

Perhaps you could perform a seek (to a specific timecode) after playback has started, but that's not ideal, and wouldn't work with `playw`.

**Comment by desepticon** [comment]
Thanks for your input.
