### ISSUE TITLE
osmc with texturecache

### ISSUE THREAD

**Issue by tyctor** [MilhouseVH/texturecache.py#66]
i am using texturecache to turn off display when nothing is playing
previously i had it on own rasbian with kodi, and it works as expected
now i switched to osmc and it works again but with one difference
it also restart kodi after i wake up it from remote 
on previous system it just wake up kodi in same state as was before sleep

i am using this command as systemd service:

```
texturecache.py @xbmc.host=localhost rbphdmi 30
```

is there any reason why kodi in osmc is restarted after waking up from sleep?

**Comment by MilhouseVH** [comment]
Presumably Kodi on Raspbian supports suspend but Kodi on OSMC does not, so in the case of the latter Kodi must be restarted - see: https://github.com/MilhouseVH/texturecache.py/blob/56e2e04cc81472579bdd8b974ee4290dbb638508/texturecache.py#L1452-L1455

The state of `cansuspend` is logged in the texturecache.py log so compare the values logged by Raspbian and OSMC.

However, `rbphdmi` is now obsolete as it was just a hack from years ago - the [pidisplaypower](https://github.com/asavah/script.pidisplaypower) addon is a much more appropriate solution for RPi0/RPi1/RPi2/RPi3 while using MMAL (I don't think it's needed at all for RPi4, or what the situation is with gbm as I'm out of touch with all this stuff now).

**Comment by tyctor** [comment]
ok, understand
thanks for answer and your hint
