### ISSUE TITLE
Python3 compatibility (or I am missing something)

### ISSUE THREAD

**Issue by pitsi** [MilhouseVH/texturecache.py#68]
Now that kodi was updated to v19 and is built with python3, I finally removed every single lib of python2 and python2 itself from my system.
And since then, I get this everytime I run texturecache and with any parameter
```
$ texturecache.py 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```
What happened?
Debian testing/unstable x64, python3 3.9.1, texturecache 2.5.4 from this git repo.

**Comment by MilhouseVH** [comment]
I think you've broken your Python installation.

**Comment by pitsi** [comment]
Lol ok. Any ideas for troubleshooting? I will also ask a friend for help. 
I get the same result when I run it on my deban unstable 32bit machine with the same python3 version. This one does not run kodi, so python2 was removed from this one in late 2019 with the last app that needed it. It is the first time I run texturecache there though.

Btw, the other standalone "app" (= a big python script that does stuff) that I have and is based on python3, tremc, works with no issues. However, it had some serious issues when my systems were upgraded to python 3.9 and since there is no stable version of it yet, I now use its git version that is 100% compatible with python 3.9.

**Comment by pitsi** [comment]
Found it! For some strange reason, the `/usr/bin/env python` part calls python2
```
$ /usr/bin/env python --version
Python 2.7.18
```
and python2 has no libraries to work at all. Changing it to `/usr/bin/env python3` makes texturecache work again.

The worse part is that /usr/bin/python is not a symlink to something but the actual executable of python2!
```
$ file /usr/bin/python
/usr/bin/python: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7152afe97c52ab4844ebbbafd9f753a50921b7d5, for GNU/Linux 3.2.0, stripped
```
I am off to complain to my distro's maintainers.

**Comment by MilhouseVH** [comment]
Glad you got to the bottom of it. :smile: 

Ubuntu has the `python-is-python3` package so that the `python` symbolic link points at `python3`.

On Debian, apparently you're supposed to use the `update-alternatives` [script](https://linuxconfig.org/how-to-change-default-python-version-on-debian-9-stretch-linux).

At some point I guess Python3-only scripts will just hard code `#!/usr/bin/env python3` (which is also the Debian Python policy) but scripts like `texturecache.py` that (currently) support both Python2 and Python3 are kind of stuck with the `python` symbolic link solution...

**Comment by pitsi** [comment]
The update-alternatives method, as described above, needs a lot of work for python because python is not one of the "options" it supports. Luckily, python-is-python3 exists for debian testing and unstable as well. Thank you for pointing it out.

I will install it once my friend confirms he has the same binary in /usr/bin/python, so as to complete my bug report. If not, I have probably done some big mistake in the past, e.g. copying /usr/bin/python2 to /usr/bin/python instead of symlinking it.

**Comment by pitsi** [comment]
My friend said that he does not have the binary at the same place. Actually, I think his reply says everything about my goof
"What type of a pebcak user COPIED the executable instead of symlinking it?!"

Thank for your support though :)
