### ISSUE TITLE
Any help is welcome

### ISSUE THREAD

**Issue by tfonias74** [MilhouseVH/texturecache.py#74]
For some time now I cannot use the "c" option and get the below errors:

_pi@pi4:~ $ ./texturecache.py c
Traceback (most recent call last):
  File "./texturecache.py", line 8663, in <module>
    main(sys.argv[1:])
  File "./texturecache.py", line 8353, in main
    if not checkConfig(argv[0]): sys.exit(2)
  File "./texturecache.py", line 7893, in checkConfig
    data = wcomms.sendJSON(REQUEST, "libPing", checkResult=False, useWebServer=True)
  File "./texturecache.py", line 2230, in sendJSON
    return self.sendWeb("POST", "/jsonrpc", id, request, {"Content-Type": "application/json"}, timeout=timeout)
  File "./texturecache.py", line 2217, in sendWeb
    return json.loads(data) if data != "" else ""
  File "/home/pi/.pyenv/versions/2.7.18/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/pi/.pyenv/versions/2.7.18/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/pi/.pyenv/versions/2.7.18/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded_

I had updated the python version to 3.x for some time and thought that this was the problem, I have just now managed to test it with 2.7.18 but the error is the same.

Any ideas?

**Comment by rainman74** [comment]
> For some time now I cannot use the "c" option and get the below errors:
> ...
> Any ideas?

Your config is not configured correctly.

Please add:
1. your texturecache.cfg
2. a screenshot of Kodi: Settings - Services - Control
3. advancedsettings.xml - if you have one

It is also better to ask the question here in the official thread, as it is not an issue: https://forum.kodi.tv/showthread.php?tid=158373

**Comment by tfonias74** [comment]
Hello and sorry for the delay.

Before adding the info requested, first I wanted to mention that other stuff is working, like status, monitor, vscan, vclean, P, etc.

https://photos.fife.usercontent.google.com/pw/AP1GczNBP-SHuLCMylkna8mXSHZhkLkDL6jlY5Qpis8enFaDOsTlELImlpp9uw=w1920-h866-s-no?authuser=0 (settings/services/control).

cat texturecache.cfg
sep = |
userdata = /mnt/Kodi
dbfile = Database/Textures13.db
thumbnails = Thumbnails
xbmc.host = 192.168.178.60
webserver.port = 8080
webserver.username = kodi
webserver.password = kodi
rpc.port = 9090
download.threads = 3
extrajson.albums =
extrajson.artists =
extrajson.songs =
extrajson.movies =
extrajson.sets =
extrajson.tvshows.tvshow =
extrajson.tvshows.season =
extrajson.tvshows.episode =
qaperiod = 30
qa.file = no
qa.fail.urls = ^video, ^music
qa.warn.urls =
cache.castthumb = no
cache.hideallitems = no
cache.ignore.types = ^video
prune.retain.types =
prune.retain.previews = yes
prune.retain.pictures = no
logfile = texturecache.log
logfile.verbose = yes
checkupdate = yes
lastrunfile =
orphan.limit.check = yes
nonmedia.filetypes =
watched.overwrite = no
network.mac =
imdb.fields.movies = rating, votes, top250
imdb.fields.tvshows = rating, votes
purge.minlen = 5
bin.tvservice = /usr/bin/tvservice
hdmi.force.hotplug = no

[advancedsettings.zip](https://github.com/MilhouseVH/texturecache.py/files/15158964/advancedsettings.zip)

**Comment by rainman74** [comment]
> Hello and sorry for the delay.

The image cannot be displayed, please resend via https://imgur.com/

But I assume that `userdata = /mnt/Kodi` is the problem
Just comment this line out: `#userdata = /mnt/Kodi`

**Comment by tfonias74** [comment]
Here https://imgur.com/a/9K2iwCr

I will try with the line commented out and revert.

BTW, do you know of an SSH server for android that works ok? Mine keeps crashing. (Kodi runs on an Android TV device, rooted).

**Comment by rainman74** [comment]
> SSH server for android

Your settings all fit, I think it will only be due to the wrong userdata path.

SSH server: SimpleSSHD

**Comment by tfonias74** [comment]
First of all thank you for your time.

After several attempts, I have the following (after changing the http port):
_Traceback (most recent call last):
  File "./texturecache.py", line 8663, in <module>
    main(sys.argv[1:])
  File "./texturecache.py", line 8353, in main
    if not checkConfig(argv[0]): sys.exit(2)
  File "./texturecache.py", line 7893, in checkConfig
    data = wcomms.sendJSON(REQUEST, "libPing", checkResult=False, useWebServer=True)
  File "./texturecache.py", line 2230, in sendJSON
    return self.sendWeb("POST", "/jsonrpc", id, request, {"Content-Type": "application/json"}, timeout=timeout)
  File "./texturecache.py", line 2177, in sendWeb
    raise httplib.HTTPException("Remote web host requires webserver.username/webserver.password properties")
httplib.HTTPException: Remote web host requires webserver.username/webserver.password properties_

One last thing, the creation of files (artwork) is it done by kodi or the script (on another PC via a mounted drive to the userdata path?

**Comment by rainman74** [comment]
> First of all thank you for your time.

Deactivate authentication for testing purposes.

![2024-05-01_135125](https://github.com/MilhouseVH/texturecache.py/assets/16306963/3b001c8e-01e4-4276-8660-52c937e7e31e)

The generation of image files is always performed by Kodi, not by the script itself.

**Comment by tfonias74** [comment]
Thanks, the problem was with port 8080 being occupied from the sshd program (didn't know it was utilizing it). After changing it on kodi and seeing the authentication messages, as you mentioned, it was clear then.
Finally it is working now. Thank you again.

**Comment by tfonias74** [comment]
thank you
