### ISSUE TITLE
Limiting imdb queries

### ISSUE THREAD

**Issue by tfonias74** [MilhouseVH/texturecache.py#76]
Hello, is there a way to limit the imdb queries (I have a 1000 per day key limit for omdb) besides movies or tv shows?

**Comment by rainman74** [comment]
> Hello, is there a way to limit the imdb queries (I have a 1000 per day key limit for omdb) besides movies or tv shows?

Please do not open “issues” (these are usually error messages) in Github, but ask your questions in the forum. There is a greater chance that they will be answered ;-)

https://forum.kodi.tv/showthread.php?tid=158373

**Comment by tfonias74** [comment]
Sorry, I know it is not an issue, but isn't the forum just for Kodi?
Anyway closing it.
